baseURL = "https://rosshudson.co.uk"
languageCode = "en-gb"
title = "rosshudson.co.uk"
theme = "ubuntu-term"

[params]
  tagline = "A place for stuff to be"
  twitter = "hossrudson"
  github = "honeypieio"
  google_site_verification = "MlDTC8ydBAgV8T7pPAbPwFIev-DpgKO5VaxT6L6XDqw"
  taglines = [
    "The walrus was Paul",
    "\"It came in a vision – a man appeared on a flaming pie and said unto them, 'from this day on you are Beatles with an A.'\"",
    "The only lonely place is on the moon 🌙",
    "What's yours?",
    "The world isn't yours, or an oyster",
    "Crooks and grannies",
    "Home for tea?",
    "Sour milk pee"
    ]
